export const getMarvelDataConstants = {
    GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
    SEARCH_CHARACTER: 'SEARCH_CHARACTER',
    //GET_INFO_SELECTED_CHARACTER: 'GET_INFO_SELECTED_CHARACTER',
    FAVORITE_CHARACTERS: 'FAVORITE_CHARACTERS',

    GET_ALL_COMICS: 'GET_ALL_COMICS',
    SEARCH_COMIC: 'SEARCH_COMIC',
    FAVORITE_COMICS: 'FAVORITE_COMICS',

    GET_ALL_EVENTS: 'GET_ALL_EVENTS',
    SEARCH_FOR_SINGLE_EVENT: 'SEARCH_FOR_SINGLE_EVENT',
    FAVORITE_EVENTS: 'FAVORITE_EVENTS',

    GET_ALL_STORIES: 'GET_ALL_STORIES',
    SEARCH_FOR_STORY: 'SEARCH_FOR_STORY',
    FAVORITE_STORIES: 'FAVORITE_STORIES',

    GET_ALL_SERIES: 'GET_ALL_SERIES',
    SEARCH_FOR_SERIE: 'SEARCH_FOR_SERIE',
    FAVORITE_SERIES: 'FAVORITE_SERIES',

    LOADING: 'LOADING',
    SET_ERROR_ACTION: 'SET_ERROR_ACTION',
    PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
    




};