export const getMarvelDataConstants = {
    GET_ALL_CHARACTERS: 'GET_ALL_CHARACTERS',
    SEARCH_CHARACTER: 'SEARCH_CHARACTER',
    GET_CHARACTER_DETAIL: 'GET_CHARACTER_DETAIL',
    FAVORITE_CHARACTERS: 'FAVORITE_CHARACTERS',

    GET_ALL_COMICS: 'GET_ALL_COMICS',
    SEARCH_COMIC: 'SEARCH_COMIC',
    GET_SINGLE_COMIC : 'GET_SINGLE_COMIC',
    FAVORITE_COMICS: 'FAVORITE_COMICS',

    GET_ALL_EVENTS: 'GET_ALL_EVENTS',
    SEARCH_FOR_SINGLE_EVENT: 'SEARCH_FOR_SINGLE_EVENT',
    EVENT_DETAILS: 'EVENT_DETAILS',

    LOADING: 'LOADING',
    UNLOADING: 'UNLOADING',
    SET_ERROR: 'SET_ERROR',
    PAGE_NOT_FOUND: 'PAGE_NOT_FOUND',
    
}